version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3500:3500'
    environment:
      - PORT=3500
      - NODE_ENV=production
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9094:9092'
    environment:
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_SYNC_LIMIT: 2  
  
  
  ##zookeeper:
    #image: wurstmeister/zookeeper:latest
    #ports:
     # - '2181:2181'
